# action.yml
name: 'Hello World'
description: 'Greet someone and record the time'
inputs:
  requirements-file:
    description: 'pip requirements file'
    required: false
    default: 'requirements.txt'
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.requirements-file }}