# action.yml
name: 'nogil/python'
description: 'Run, Build, and Test Python Code in Multithreaded Python without the GIL'
inputs:
  requirements-file:
    description: 'pip requirements file'
    required: false
    default: 'requirements.txt'
  command:
    description: 'command to execute'
    required: true
  command2:
    description: 'command to execute'
    required: false
  command3:
    description: 'command to execute'
    required: false
  command4:
    description: 'command to execute'
    required: false
  command5:
    description: 'command to execute'
    required: false
  command6:
    description: 'command to execute'
    required: false
outputs:
  time: # id of output
    description: 'The time we greeted you'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.requirements-file }}
    - ${{ inputs.command }}
    - ${{ inputs.command2 }}
    - ${{ inputs.command3 }}
    - ${{ inputs.command4 }}
    - ${{ inputs.command5 }}
    - ${{ inputs.command6 }}
